### ISSUE TITLE
Text not rendering on first render

### ISSUE THREAD

**Issue by KrisLau** [enzomanuelmangano/react-native-skia-gesture#1] opened 2023-02-10 17:13 UTC
When the component first renders, the Text is not rendering. The moment I drag the item, the text renders immediately. 

Initial render:
![image](https://user-images.githubusercontent.com/46275463/218153581-ca4b89ff-1593-43a1-8572-4c972e59adb4.png)

After dragging:
![image](https://user-images.githubusercontent.com/46275463/218153750-9e1e0359-cd02-4e1f-8332-55bc3ba768bd.png)

Tested and weirdly only happens with Touchable and this component even though I have another component that is almost exactly the same. Another weird thing is that when I use `useComputedValue` for the text instead of `useValue`, even when I drag it doesn't show the text.

Ok so when I replace the text x and y vales with static ones it shows up but then the drag is frozen.

https://snack.expo.dev/@kris_lau/text-no-render

**Comment by enzomanuelmangano** [comment] 2023-02-11 21:46
Hi @KrisLau thanks for opening the issue. 
I tried your demo and replicated the error you mention. I would like to mention that React Native Skia Gesture is a package that is only concerned with implementing gestures on Canvas elements. The error encountered here occurs independently of react-native-skia-gesture. 

In particular, the problem is caused by the fact that "**textXOffset**" must be a computed value because it depends on font. You experience the problem because the first time font is undefined and only after rendering, it is updated correctly.   

```tsx 
const textXOffset = useComputedValue(
  () => props.size / 2 - props.font?.getTextWidth(name) / 1.9,
  [props.font]
);
``` 

Clearly, it is also necessary to update the textCx dependencies: 

```tsx 
const textCX = useComputedValue(
  () => innerCX.current + textXOffset.current,
  [outerCX, textXOffset]
);
```

Hope it helps! I will close the issue, but feel free to comment again if you don't think the issue is resolved.

**Closed by enzomanuelmangano** 2023-02-11 21:46 UTC

**Comment by KrisLau** [comment] 2023-02-13 15:03
Thank you so much just adding the offset to the dependencies fixed it! Didn't need to make the offset into a computed value

**Comment by enzomanuelmangano** [comment] 2023-02-13 16:10
Hi @KrisLau, in order to create a **TouchableImage** you need to define the component by using the **withTouchableHandler** HOC: 

```ts
import { Image } from '@shopify/react-native-skia';
import { withTouchableHandler } from 'react-native-skia-gesture';

const TouchableImage = withTouchableHandler(Image);
```

Then, as you mentioned, you need to pass the path to it. That's done automatically for **Rect**, **RoundedRect** and **Circle**. Maybe in next versions I'll handle automatically the path for the Image as well!

**Comment by KrisLau** [comment] 2023-02-13 16:19
@enzomanuelmangano Sorry just saw this and yup I figured it out by going through the code more and created a PR to add a clarification to the docs, thanks so much!

**Comment by KrisLau** [comment] 2023-02-23 20:29
@enzomanuelmangano Sorry hope you don't mind me using this issue to ask a different question but I didn't wanna create an issue since it's more of a problem with my code! 

Getting the `Too many re-renders` error. I know why I am getting the error but I'm unsure how to refactor it. I'm probably just overlooking a super simple explanation but any help/ideas is appreciated. Basically when I drag the item on my canvas, I want to check where the user drags and drops it to. Based on where they drop the item I want to show different overlay content

My code:
```jsx
// firstBaseRunner is also used to render a different component
const firstBaseRunner = {
  ...
  gestureHandler: useGestureHandler({
    ...
    onEnd: () => {
      const results = checkBounds()
    },
  }) 
}
function checkBounds() {
  const result = {...}
  setIsVisible(true); 
  setSafeOutResult(result); // removing this gets it to work
  return result;
}
```
```jsx
<MyComponent 
  safeOutResult={safeOutResult} // removing this gets it to work
/>
```
Not sure how to refactor it since I do need `safeOutResult` in the component
