### ISSUE TITLE
Crash app when I build iOS adhoc 

### ISSUE THREAD

**Issue by hoanjizi** [enzomanuelmangano/react-native-skia-gesture#4] opened 2023-04-17 03:36 UTC
Hi there I'm using lib for touch on element of skia it work correctly on debug mode (on simulator and real device) but it crash when I touch element on build with adhoc (release mode). please help me check it 
React info:
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 882.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.6.0 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/hoan/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.8 => 0.70.8 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
    
    
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/19235518/232372095-a42bd0d7-1553-4691-9bc4-84ef46351b6f.png">

**Comment by hoanjizi** [comment] 2023-04-17 04:51
I install firebase crashlytics and it show below:

Fatal Exception: RCTFatalException: non-std C++ exception
0  CoreFoundation                 0x9e48 __exceptionPreprocess
1  libobjc.A.dylib                0x178d8 objc_exception_throw
2  *                         0xfdcc0 RCTFormatError + 167 (RCTAssert.m:167)
3  *                         0x113334 -[RCTCxxBridge handleError:] + 1180 (RCTCxxBridge.mm:1180)
4  *                         0x111bd0 __34-[RCTCxxBridge _initializeBridge:]_block_invoke + 688 (RCTCxxBridge.mm:688)
5  *                         0x124df0 facebook::react::RCTMessageThread::tryFunc(std::__1::function<void ()> const&) + 73 (RCTMessageThread.mm:73)
6  *                         0x124b84 invocation function for block in facebook::react::RCTMessageThread::runAsync(std::__1::function<void ()>) + 46 (RCTMessageThread.mm:46)
7  CoreFoundation                 0x43524 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__
8  CoreFoundation                 0xabd7c __CFRunLoopDoBlocks
9  CoreFoundation                 0x7c1dc __CFRunLoopRun
10 CoreFoundation                 0x80ec0 CFRunLoopRunSpecific
11 *                         0x10f594 +[RCTCxxBridge runRunLoop] + 335 (RCTCxxBridge.mm:335)
12 Foundation                     0x5b5a8 __NSThread__start__
13 libsystem_pthread.dylib        0x16cc _pthread_start
14 libsystem_pthread.dylib        0xba4 thread_start

**Comment by enzomanuelmangano** [comment] 2023-05-01 12:38
Hi @hoanjizi, thanks for opening an issue.
I was able to reproduce the same error while using **Skia Selectors**. I've fixed the bug in the latest version of r**eact-native-skia-gesture** (v0.1.172). 

By the way I've noticed in your code something strange. I believe you can't pass **roundedRectX.current** and **roundedRectY.current** to your **ButtonImage** component (you simply need to pass **roundedRectX** and **roundedRectY**). 

Let me know if it works :) 

Note: I'm going to close the issue for now, if you thing that the issue is still not solved, feel free to reopen it.

**Closed by enzomanuelmangano** 2023-05-01 12:38 UTC
